### ISSUE TITLE
MinGW 8.1.0不支持C++17 filesystem

### ISSUE THREAD

**Issue by L-Super** [orestonce/install-qt-static#2]
在使用的时候，发现对应的MinGW编译器版本似乎过低，导致不支持C++17部分新特性，目前已知不支持filesystem。后续可否提供更高版本的MinGW编译器，或更高版本的Qt，以支持C++17特性

**Comment by L-Super** [comment]
我通过egor-tensin/setup-mingw安装更高MinGW版本解决问题，但是Qt库编译又出现问题：
```
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\MTool.dir/objects.a(mocs_compilation.cpp.obj):mocs_compilation.cpp:(.text+0x1c): undefined reference to `QObjectData::dynamicMetaObject() const'
```

**Comment by orestonce** [comment]
我用的这个 https://build-qt.fsu0413.me/ 上面的，没有自己编译。

**Comment by L-Super** [comment]
> 我用的这个 https://build-qt.fsu0413.me/ 上面的，没有自己编译。

这上面有更高版本的MinGW Qt5，后续能加进来吗

**Comment by orestonce** [comment]
可以的

**Comment by orestonce** [comment]
orestonce/install-qt-static@v0.4.3 已支持 Qt6.5.3-Windows-x86_64-MinGW13.2.0-ucrt-staticFull-20240527

**Comment by L-Super** [comment]
> orestonce/install-qt-static@v0.4.3 已支持 Qt6.5.3-Windows-x86_64-MinGW13.2.0-ucrt-staticFull-20240527
> 

感谢大佬
