### ISSUE TITLE
能否更新更多个Qt静态版本

### ISSUE THREAD

**Issue by davidche1116** [orestonce/install-qt-static#3]
看https://github.com/Fsu0413/QtCompile已经支持很多新的了

**Comment by orestonce** [comment]
可以看看这个 https://github.com/orestonce/install-qt

**Comment by davidche1116** [comment]
666，这个更新到最新的6.7.2了！

**Comment by davidche1116** [comment]
……白高兴了，https://build-qt.fsu0413.me/    里6.7.2也是动态的，不是静态……

**Comment by orestonce** [comment]
hahaha，可以在这里 https://github.com/Fsu0413/QtCompile/issues/31 催更他一下

**Comment by davidche1116** [comment]
看到了，他说双十一买新机
